### ISSUE TITLE
liveserver fixture

### ISSUE THREAD

**Issue by Centuriondan** [idlesign/pytest-djangoapp#24]
A key fixture missing when switching from pytest-django is the liveserver fixture which I use for running selenium based functional tests (TDD).

Is there an intention to add a live_server fixture that will have a similar effect as in pytest_django?

**Comment by idlesign** [comment]
Thank you for the idea.
We probably could add this feature, it'd take a while to think it over and design API.

**Comment by idlesign** [comment]
liveserver and liveclient fixtures are now available in 1.2.0. 
https://pytest-djangoapp.readthedocs.io/en/latest/fixtures_live.html

Feel free to check those out.
Considered closed.
