### ISSUE TITLE
Is there some way to get coverage of django project which testcase is written in tavern?

### ISSUE THREAD

**Issue by iakirago** [idlesign/pytest-djangoapp#27]
I have a django project, which testcase is written in tavern. 
Run manage.py in the screen before, execute pytest outside the screen, wait until the test execution is completed, use kill -2 to kill the manage.py process, and then use coverage report and coverage html to get coverage and coverage report files.Every testcase is running success,  the coverage is 80 percent.
If do not run manage.py in screen, the coverage is always 10% when every testcase run success.

I hope to know if there is some way to get the right coverage without running in screen.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
