### ISSUE TITLE
Failure on Django 3.0 or lower if no tables were created

### ISSUE THREAD

**Issue by jayvdb** [idlesign/pytest-djangoapp#7]
I am using pytest-djangoapp with django-fake-model, and the tear-down is unnecessarily failing on Django 3.0.  On Django master (3.1-ish) there are no errors.  So it seems the `# todo optional db initialization` is magically done on Django 3.1, and it might be possibly to find the fix in Django 3.1 and simulate it for earlier Django.

```py
________________________________________________________________________ ERROR at teardown of test_abc ________________________________________________________________________

item = <Function test_xyz>, nextitem = <Function test_abc>

    def pytest_runtest_teardown(item, nextitem):
        unset = {}
    
        old_config = getattr(item, 'old_config', unset)
    
        if old_config is unset:
            # _teardown will suddenly work even if no _setup has occured
            # e.g. in case of mark.skipif
            return
    
>       call_command('flush', interactive=False)

/usr/lib/python3.8/site-packages/pytest_djangoapp/plugin.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.8/site-packages/django/core/management/__init__.py:168: in call_command
    return command.execute(*args, **defaults)
/usr/lib/python3.8/site-packages/django/core/management/base.py:369: in execute
    output = self.handle(*args, **options)
/usr/lib/python3.8/site-packages/django/core/management/commands/flush.py:47: in handle
    sql_list = sql_flush(self.style, connection, only_django=True,
/usr/lib/python3.8/site-packages/django/core/management/sql.py:16: in sql_flush
    seqs = connection.introspection.sequence_list() if reset_sequences else ()
/usr/lib/python3.8/site-packages/django/db/backends/base/introspection.py:116: in sequence_list
    sequence_list.extend(self.get_sequences(cursor, model._meta.db_table, model._meta.local_fields))
/usr/lib/python3.8/site-packages/django/db/backends/sqlite3/introspection.py:91: in get_sequences
    pk_col = self.get_primary_key_column(cursor, table_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <django.db.backends.sqlite3.introspection.DatabaseIntrospection object at 0x7fbe45ea88b0>, cursor = <django.db.backends.utils.CursorWrapper object at 0x7fbe346bab80>
table_name = 'myapp_default'

    def get_primary_key_column(self, cursor, table_name):
        """Return the column name of the primary key for the given table."""
        # Don't use PRAGMA because that causes issues with some transactions
        cursor.execute(
            "SELECT sql, type FROM sqlite_master "
            "WHERE tbl_name = %s AND type IN ('table', 'view')",
            [table_name]
        )
        row = cursor.fetchone()
        if row is None:
>           raise ValueError("Table %s does not exist" % table_name)
E           ValueError: Table myapp_default does not exist

/usr/lib/python3.8/site-packages/django/db/backends/sqlite3/introspection.py:191: ValueError
```

**Comment by jayvdb** [comment]
Perhaps a better approach is to find/create a database driver which fails on any write operation, and then can do nothing on db close/flush/etc.  Then the test harness/case is explicitly declaring that it doesnt need to write, and that assertion is being checked.

**Comment by jayvdb** [comment]
Setting `flush` hidden option `reset_sequences=False` seems to do the trick.  `flash` has two other hidden options, `allow_cascade` and `inhibit_post_migrate`.  It would be nice to expose them all as `configure_djangoapp_plugin` args or settings or even via fixtures to each test.

```diff
diff --git a/pytest_djangoapp/plugin.py b/pytest_djangoapp/plugin.py
index b65b555..5379621 100644
--- a/pytest_djangoapp/plugin.py
+++ b/pytest_djangoapp/plugin.py
@@ -36,7 +36,7 @@ def pytest_runtest_teardown(item, nextitem):
         # e.g. in case of mark.skipif
         return
 
-    call_command('flush', interactive=False)
+    call_command('flush', interactive=False, reset_sequences=False)
     teardown_databases(old_config)
 
 
```

**Comment by idlesign** [comment]
For history:
```
The sequences positional argument of DatabaseOperations.sql_flush() is replaced by the boolean keyword-only argument reset_sequences. If True, the sequences of the truncated tables will be reset.
```
[from here](https://docs.djangoproject.com/en/3.1/releases/3.1/#database-backend-api)

**Comment by jayvdb** [comment]
https://github.com/kamilkijak/django-smoke-tests/blob/master/django_smoke_tests/runners.py and https://github.com/weeksghost/dj-nodb/issues/1 are two instances of test runners that ignore db setup and teardown. I found that didnt work, possibly because of Django 3, or some other factor with my small zero-models project, but it seems it does work for some situations.

It wont allow a mix of tests that use or not-use db, but it could be helpful.  I'll try some other Django versions today to see if it is just a Django 3 thing.

**Comment by jayvdb** [comment]
An aside/background

The project I was building : https://github.com/jayvdb/django-dunder

It turns out that the mere presence of `models.py` in the app causes lots of problems with the Django db initialisation of the test models, even if the app has no real models in the file.  The funky solution that appears to work is implementing `AppConfig.get_models()` to return `[]`

**Comment by jayvdb** [comment]
pytest-django has a fixture `django_db_reset_sequences` which enables this, but otherwise defaults to false.
https://github.com/pytest-dev/pytest-django/blob/master/docs/helpers.rst

pytest-django has no support for tweaking `allow_cascade` or `inhibit_post_migrate`.
